### PR TITLE
introduced automatic combinator instead of typing guesses 

### PR DESCRIPTION
**Pull request by dhanushnatra**
made changes that simplifies the complexity
and introduced combiner for simple and unhuman effort in typing
run my code and check  for any issues : )

### CODE REVIEW

**Comment by sina-programer** [comment]
Tnx a lot my friend! In real world passwords are much more hard to guess! For a more performance we need a program to check more usual passwords and we get them from a pass-list. But I love your idea about a new way to find different passwords without using a password-list; I was thinking about some methods like an inside-genrator! Yeah we can generate passwords and use them instantly. There are some other ways to have passwords for testing and maybe later we make this as an option to make other ways choosable for end-user to decide which method is more suitable for a desired target. But this lateness in answering and postpone in progressing the repo is all for the heavy work-related stuff and I am too busy. Overall I appreciate your tries and the enthusiasm; It's really valueable at least for me because in the begining I was very curious too and I hope you'll be very successful in your careet especially in python related topics. Wish the best for you dear.

**Comment by dhanushnatra** [comment]
i am not hoping for a reply actually .....this actually increases my will
to contribute ....thanks for support,understanding and reply .....thanks
for considering about my future .....i will consider making a yes or no
option to select users will to use custom passwords or instantly combined
passwords...

**Comment by sina-programer** [comment]
It'll be my honor to have you and your help by my repo. But I am kinda quixotic for my projects ,so we I just accept changes which are completely nice and clean. I really don't like to force users to do what we want; They should decide themselves with freedom about thier stuff. In fact I like to provide a wide range of options to users to choose. It's better if we don't make a 'yes | no' option and a more compatible method that if we had three or more options we still be able to use that method. In short, you can just write the functions and methods to create passwords and I will implement them, it'll be your duty if you want to contribute.

**Comment by dhanushnatra** [comment]
cool i will do if i got some time

**Pull request closed without merging**
